- server/Dockerfile
- server/cfg/context.go
- server/log/log.go
- server/server.go
- server/service/service.go
- server/web/routes.go
Here are minimal requirement to run Pillar in a Docker container:
> The app must be able to read mongo credentials and any other info
> The app must write log files to a certain location
Proposed Solution:
Define an env variable ```PILLAR_HOME``` to a location where the server will be deployed.
~~~
export PILLAR_HOME=/opt/pillar
~~~
The server expects to read various information from ```$PILLAR_HOME/pillar.json``` file. Here is how this might look:
~~~
{    
"mongo_url": "mongodb://localhost:27017/coral"
}
~~~
Runtime, the server will write logs to ```$PILLAR_HOME/logs/pillar.log```
> Fix for https://github.com/coralproject/pillar/issues/16

- app/pillar/handler/handler.go
- app/pillar/route/routes.go
- pkg/model/model.go
- pkg/service/asset.go
- pkg/service/comment.go
- pkg/service/service.go
- pkg/service/user.go
- test/fixtures/assets.json
- test/fixtures/tags.json
- test/service_test.go
(a) Two new structures created:
> Tag
> Tagstat
(b) end-point api/tag created to create/update master tag
(c) when tags come-in for various entities, we build the tagstat - coming...
> Issue #9 - Tag related end-point and other changes

- pkg/crud/action.go
- pkg/crud/asset.go
- pkg/crud/comment.go
- pkg/crud/fixtures/actions.json
- pkg/crud/fixtures/indexes.json
- pkg/crud/fixtures/metadata.json
- pkg/crud/model.go
- pkg/crud/note.go
- pkg/crud/service.go
- pkg/crud/service_test.go
- pkg/crud/user.go
> Fix for Issue#30 - all plural names for collections.

- pkg/crud/asset.go
- pkg/crud/comment.go
- pkg/crud/service_test.go
- pkg/crud/user.go
> Fix for Issue#29 - Upsert when entity exists.

- app/pillar/handler/handler.go
- app/pillar/handler/tag.go
- app/pillar/main.go
- app/pillar/route/routes.go
- config/dev.cfg
- config/localhost.cfg
- vendor/vendor.json
> Issue #39 - support pre-flight requests

- pkg/crud/action.go
- pkg/crud/comment.go
- pkg/crud/fixtures/actions.json
- pkg/crud/service.go
- pkg/crud/service_test.go
- pkg/crud/tag.go
- pkg/crud/user.go
> Issue #45 - Prevent duplicate action.

- pkg/model/asset.go
- pkg/model/author.go
> Authors, section and subsection.

- app/pillar/handler/handler.go
- app/pillar/route/routes.go
- pkg/model/model.go
- pkg/service/fixtures/user-actions.json
- pkg/service/service.go
- pkg/service/service_test.go
> Log User Activity in Mongo

- app/pillar/handler/updater.go
- app/pillar/route/routes.go
- pkg/service/asset.go
- pkg/service/comment.go
- pkg/service/user.go
New end-points created to update tags.
~~~
/api/asset
/api/user
/api/comment
~~~
Pass tags for an entity. Here is an example json for a user:
~~~
{
"id" : "56ce75ae1fefce879a9e1b58",
"tags" : ["xyz", "hello"]
}
~~~
> Issue#56 - update tags for asset, user and comment.

- app/stats/calc/calc.go
- app/stats/stats.go
- pkg/aggregate/float64.go
- pkg/aggregate/int.go
- pkg/aggregate/pipeline.go
- pkg/backend/backend.go
- pkg/backend/backend_test.go
- pkg/backend/iterator/iterator.go
- pkg/backend/mongodb/mongodb.go
- pkg/model/object.go
- pkg/model/statistics/action.go
- pkg/model/statistics/comment.go
- pkg/model/statistics/user.go
- pkg/model/statistics/user_test.go
Merging to coralproject to resolve vendor issues.
> Statistics refactor

- app/pillar/handler/tag.go
- app/pillar/route/routes.go
- pkg/model/tag.go
- pkg/service/asset.go
- pkg/service/fixtures/tags.json
- pkg/service/fixtures/tags_rename.json
- pkg/service/fixtures/users.json
- pkg/service/service_test.go
- pkg/service/tag.go
> Issue#56 - rename tags and update users.

- pkg/db/backend.go
- pkg/db/iterator.go
- pkg/db/mongodb.go
Usage:
~~~
db := db.NewMongoDB()
defer db.Close()
db.Find(...)
db.Upsert(...)
~~~
Hey @buth, I've merged your ```backend``` package with my code on mongodb. This is all in ```db``` package. Let's look at this together when you're ready.
> Issue#60 - new db package with backend and iterator.

- app/pillar/handler/handler.go
- app/pillar/handler/importer.go
- app/pillar/handler/mware.go
- app/pillar/handler/tag.go
- app/pillar/handler/updater.go
- app/pillar/main.go
- app/pillar/route/router.go
- app/pillar/test/fixtures/actions.json
- app/pillar/test/fixtures/assets.json
- app/pillar/test/fixtures/comments.json
- app/pillar/test/fixtures/indexes.json
- app/pillar/test/fixtures/metadata.json
- app/pillar/test/fixtures/tags.json
- app/pillar/test/fixtures/tags_rename.json
- app/pillar/test/fixtures/user-actions.json
- app/pillar/test/fixtures/users.json
- app/pillar/test/pillar_test.go
- app/pillar/test/rest.go
- pkg/service/action.go
- pkg/service/asset.go
- pkg/service/comment.go
- pkg/service/note.go
- pkg/service/service.go
- pkg/service/service_test.go
- pkg/service/tag.go
- pkg/service/user.go
Part 1 - Introduced ```AppContext``` and updated service layer to use that
Part 2 - Introduced new middleware to pass ```AppContext``` to service layer.
> Issue#62 - Refactoring - Introduce a new MW, AppContext to work with handler and service layer

- pkg/db/mongodb.go
- pkg/model/model.go
- pkg/model/search.go
- pkg/service/search.go
> Issue#77 - SearchHistory introduced!

- app/pillar/handler/crud.go
- app/pillar/route/routes.go
- pkg/service/search.go
- pkg/web/web.go
find one    - GET /api/search/{id}
delete one - DELETE /api/search/{id}
Ready for review...
> Issue#83 - Single search and a single delete is taken care of using id.

- app/pillar/test/pillar_test.go
- pkg/model/action.go
- pkg/model/asset.go
- pkg/model/author.go
- pkg/model/comment.go
- pkg/model/dimension.go
- pkg/model/model.go
- pkg/model/note.go
- pkg/model/search.go
- pkg/model/section.go
- pkg/model/tag.go
- pkg/model/user.go
- pkg/service/action.go
- pkg/service/asset.go
- pkg/service/author.go
- pkg/service/comment.go
- pkg/service/note.go
- pkg/service/search.go
- pkg/service/section.go
- pkg/service/service.go
- pkg/service/tag.go
- pkg/service/user.go
- pkg/test/fixtures/crud/tags_rename.json
- pkg/test/model_test.go
- pkg/test/service_test.go
> Issue#90 - Better error handling

- app/pillar/handler/crud.go
- app/pillar/handler/importer.go
- pkg/amqp/amqp.go
- pkg/model/event.go
- pkg/service/asset.go
- pkg/service/service.go
- pkg/service/user.go
- pkg/web/web.go
Fix for Issue #95 
Install `Pillar` with a RabbitMQ`. Write a client to receive message from queue and you should now receive messages for all events.
> Issue#95 - a generic event dispatch.

- app/stats/atoll.go
- app/stats/calc.go
- app/stats/collection.go
- app/stats/meta.go
- app/stats/stats.go
- app/stats/timeseries.go
- pkg/model/comment.go
- pkg/model/statistics/comment.go
- pkg/model/user.go
- pkg/service/comment.go
- pkg/service/user.go
> Embedded `Actions` inside `Comment` and `User`
> Introduced `RootID` in `Comment`
> Updated `ParentID` to `Parents` as an array.
> Wapo feedback changes

- app/pillar/test/fixtures/actions.json
- app/pillar/test/fixtures/comments.json
- app/pillar/test/fixtures/users.json
- app/pillar/test/pillar_test.go
- pkg/model/action.go
- pkg/model/asset.go
- pkg/model/author.go
- pkg/model/comment.go
- pkg/model/model.go
- pkg/model/note.go
- pkg/model/search.go
- pkg/model/section.go
- pkg/model/tag.go
- pkg/model/user.go
- pkg/service/action.go
- pkg/service/comment.go
- pkg/service/service.go
- pkg/service/user.go
- pkg/test/fixtures/import/actions.json
- pkg/test/fixtures/import/comments.json
- pkg/test/fixtures/import/users.json
- pkg/test/service_test.go
- pkg/web/web.go
> Creates a new user if found in Comment.Source.User
> Creates a new user if found in Comment.Source.Action
> Create user on import Comment and Action

- app/pillar/handler/ask.go
- app/pillar/route/routes.go
- pkg/behavior/historical.go
- pkg/behavior/item.go
- pkg/model/form_gallery.go
- pkg/service/form_gallery.go
- pkg/service/form_submission.go
- pkg/test/service_test.go
Adds / fixes issues / bugs from #118 
All tests available in the pkg/test test suite
> Ask apis 3

- pkg/model/form.go
- pkg/model/form_gallery.go
- pkg/model/form_submission.go
- pkg/service/form_gallery.go
- pkg/service/form_submission.go
- pkg/test/fixtures/crud/forms.json
- pkg/test/service_test.go
> Incorporate Identity and fix miswired api

- app/pillar/handler/ask.go
- pkg/service/form_gallery.go
Hotfix for remove answer bug #121 
> Ask apis 4

- README.md
Updates the README to point to documentation and doc repository.
> Updated README to point to documentation

- pkg/model/search.go
- pkg/service/search.go
Update the search model and service to support cay save/update.
Create and update searches with cay.  
> Update search model and service

- pkg/aggregate/pipeline.go
Removes spammy logging from the stats aggregator.
Run stats and notice streamlined logging.
> Remove spammy logging

- pkg/backend/mongodb.go
- pkg/db/mongodb.go
Minor fixes to connection logic.
> Minor fixes to MongoDB

- pkg/db/mongodb.go
- pkg/model/index.go
- pkg/service/form_submission.go
- pkg/service/service.go
Adds an index on text search to the model.Indicies structure. But still ensures that the index exists when searching. 
Adds the collection name when connecting to the sessions.
@jde this is a quick PR. Can you take a look?
> Quick PR on Indexes

- pkg/db/mongodb.go
- pkg/model/index.go
- pkg/service/form_submission.go
- pkg/service/service.go
Reverts coralproject/pillar#157
> Revert "Quick PR on Indexes"

- pkg/service/form_submission.go
- click a button
- view the cat
- see the cat meow
> Change the names of the keys in the result.

- pkg/service/form_gallery.go
> Hydrate gallery before returning

- pkg/model/form_submission.go
- pkg/service/form.go
- pkg/service/form_submission.go
- pkg/test/service_test.go
> Resolve pillar issues for beta release

- app/pillar/handler/ask.go
- app/pillar/route/routes.go
- pkg/model/form_gallery.go
- pkg/service/form_gallery.go
Implements https://github.com/coralproject/pillar/issues/174
> Add edit form_gallery endpoint

- app/pillar/handler/ask.go
- app/pillar/route/routes.go
- pkg/model/form_gallery.go
- pkg/service/form_gallery.go
Bugfix for update form_gallery
> Revert "Add edit form_gallery endpoint"

- pkg/model/form.go
Adds a description field to formWidgets to satisfy this: https://github.com/coralproject/ask/issues/29
Create a form widget with a description
Save it
See that it now saves
> Add description to formWidget model

- pkg/service/form_gallery.go
- pkg/test/service_test.go
It does not really fix Issue#177 (still not sure why that error is in the log) but fix updating galleries.
It add tests to check that it works.
Update a form gallery and check that it works.
> Fix update gallery and add tests.

- app/pillar/config/config.go
Removes the file pillar.log where it was logging the errors to. And it logs everything to stdout.
> Log to stdout

- pkg/model/search.go
Adds a ExcludedTags field to a search to trace which tags are being excluded from a search
> Excluded tags
